### ISSUE TITLE
Figaro in application.rb with Rails 4.1

### ISSUE THREAD

**Issue by mahemoff** [laserlemon/figaro#107]
I've found Figaro variables are empty in application.rb (Rails 4.1).

All of the Figaro examples are about initializers, so I'm not sure if it's intended to work in application.rb, but it seems application.yml isn't parsed by then. At least with Rails 4.1.

**Comment by Carpela** [comment]
Example of where figaro (or at least application.yml) would need to be loaded before Rails.root:

Adding a custom gem from a private repo on github into a Gemfile. 
ENV['GITHUB_AUTH_TOKEN'] would be nice so that it wasn't necessary to put auth tokens in the gemfile. Not quite sure how I do that...

**Comment by laserlemon** [comment]
[Figaro 2.0](https://github.com/laserlemon/figaro/projects/1) will remove its reliance on `Rails.root` and `Rails.env`, so this should no longer be an issue when version 2.0 ships. The timing on that is still unknown though. :(
