### ISSUE TITLE
Figaro doesn't work with Rails 4.1 in test environment

### ISSUE THREAD

**Issue by aldesantis** [laserlemon/figaro#120]
I'm using Rails 4.1 and, since I prefer Figaro to the new **secrets.yml**, I installed it and put the following in **config/application.rb**:

``` ruby
# ...

module MyApp
  class Application < Rails::Application
    # ...

    config.time_zone = ENV['TIME_ZONE']
    config.i18n.default_locale = ENV['DEFAULT_LOCALE']

    # ...
  end
end
```

I also have other similar settings in my initializers, but for some reason my application doesn't see any of the environment variables in the test environment.

Is this a known issue? Do you have a workaround?

**Comment by quantumpotato** [comment]
I just installed Rails 4.2, ran the figaro installer, configured my application.yml and don't have ENV["my_api_key"] available in rails console.. is this related?

**Comment by alessandro1997** [comment]
No, this issue was caused by me putting Figaro in the **development** group of my Gemfile.

**Comment by jhubert** [comment]
Just an FYI that the recommendation to restart spring solved this issue for me. Thanks @odigity!
