### ISSUE TITLE
unable to run figaro -- missing executable

### ISSUE THREAD

**Issue by johnpaulashenfelter** [laserlemon/figaro#131]
$ bundle exec figaro
bundler: command not found: figaro
Install missing gem executables with `bundle install`

but

$ bundle list | grep fig
- figaro (0.7.0)

Really confused -- looked through the bundle and I don't see a /bin dir or anything that would create one. Tried installing gem with -binstubs, but nothing.

Am I doing something wrong or is the documentation out of date? The rake task works fine

Ruby 2.1.1
Rails 4.1.1
OSX, rbenv-managed ruby

**Comment by liang90925** [comment]
Did the following two steps:
1) make sure you have gem 'figaro', '~> 1.0.0' in your gemfile
2) from your project dir do  $ gem install figaro

But still have "-bash: figaro: command not found"
when running $ figaro heroku:set -e production

**Comment by aliehanani** [comment]
If using RVM, at the the terminal follow steps 1 & 3 on the User's' directory.

Then proceed at app directory :
1)  source /Users/*/.rvm/scripts/rvm
2) bundle install
3) gem install figaro
4) bundle exec figaro install

**Comment by lacostenycoder** [comment]
@aliehanani solution worked but without `bundle exec` just `figaro install` in last step.
