### ISSUE TITLE
Best practice for sharing application.yml internally?

### ISSUE THREAD

**Issue by hspinks** [laserlemon/figaro#146]
Hey figaro community,

Huge fan of this gem, and have been using it for some time, but have always wondered about the best ways to share the application.yml file as it's updated. The file is correctly ignored by git for security reasons, which leaves us to other methods of sharing it that aren't as accommodating for multiple people updating it. I live in fear of the day that we accidentally overwrite one of our api keys because changes aren't merged together.

Has anyone found a good, secure way of sharing an application.yml file amongst a team that doesn't have the same danger of overwriting changes?

**Comment by andrew-koster-** [comment]
@laserlemon Why is Keybase considered more secure than a private Git repository? I don't want random people having access to any part of my proprietary code, so why are we focusing specifically on API keys?
