### ISSUE TITLE
Rename default application.yml to environment.yml

### ISSUE THREAD

**Issue by stgeneral** [laserlemon/figaro#158]
I would like to suggest to rename `application.yml` to `environment.yml` because is seems more relevant to the Figaro goals:
- Figaro sets the _environment_ variables, but not _application_ settings or configuration. So, `environment.yml` looks more semantic.
- `application.yml` is a default example file to store settings for some gems like [settingslogic](https://github.com/settingslogic/settingslogic#1-define-your-class).
- Rail 4.2 introduces new `Rails::Application.config_for` feature. And I believe that a lot of users (including me) would like to store application config into the `application.yml` instead of inventing other less obvious names like app.yml, config.yml, settings.yml etc.

**Comment by n-rodriguez** [comment]
Naming the file ```figaro.yml``` would have been great.

**Comment by laserlemon** [comment]
Thanks again for the feedback. I'm afraid if I would have named it something else, it probably would have just been somebody else suggesting a change. 😃

**Comment by n-rodriguez** [comment]
> I'm afraid if I would have named it something else, it probably would have just been somebody else suggesting a change.

yes, murphy's law is not far ^^
I've finally named  SettingsLogic file ```settings.yml``` :)
