### ISSUE TITLE
figaro install doesn't work

### ISSUE THREAD

**Issue by ghost** [laserlemon/figaro#159]
The README says to install figaro by adding it to the Gemfile, running `bundle install` and then `figaro install`. This all works except the last step. `figaro install` is not a command. Neither is `rake figaro install`, `bundle exec figaro install`, or `rails figaro install`.

**Comment by anser-clustox** [comment]
Thank you so much

**Comment by arubyist** [comment]
Using `rails 4.2` and the most recent version of `figaro 1.1.0` as of this time, `figaro install` doesn't work as per instructions, FYI. 

And neither does this `rails generate figaro:install` as mentioned above work.

**Comment by laserlemon** [comment]
What does it do when it doesn't work?

**Comment by arubyist** [comment]
When I did `figaro install`, it said `-bash: figaro: command not found`.

When I tried `rails generate figaro:install` instead, it said `Could not find generator 'figaro:install'. Maybe you meant 'migration' or 'erb:mailer' or 'generator'`

As of now, I've temporarily solved the problem by reverting to the earlier version of figaro and using the latter command `rails generate figaro:install`.

**Comment by laserlemon** [comment]
What if you do `bundle exec figaro install`?

**Comment by arubyist** [comment]
Eh. Will do it in the next mini-project during this week. Don't want to revert since I've proceeded ahead on my project. 

I'll let you know!

**Comment by userium** [comment]
I had the same problem, "bundle exec figaro install" worked for me.

**Comment by jesskturner** [comment]
"bundle exec figaro install" worked for me as well, running Figaro 1.1.0.

**Comment by Sam-and-rails** [comment]
"bundle exec figaro install" also work for me, Figaro 1.1.0

**Comment by Steven3000** [comment]
"bundle exec figaro install" worked for me, Figaro 1.1.0

**Comment by sezobel** [comment]
bundle exec figaro install also worked for me but then when i run rake figaro:heroku i get rake aborted!
Don't know how to build task 'figaro:heroku'....... thoughts on how to solve that one ?

**Comment by Steven3000** [comment]
I ended up deleting figaro and updating a yml file in rails

**Comment by mojo1643** [comment]
"bundle exec figaro install" worked for me too, Figaro 1.1.0

**Comment by brian30** [comment]
I have been having the same problem with rails generate figaro:install. But after thourough search on github and stackoverflow, bundle exec figaro install has worked. Thanks buddies.

**Comment by liang90925** [comment]
bundle exec figaro install works ... BUT, $  figaro heroku:set -e production still shows -bash: figaro: command not found

**Comment by laserlemon** [comment]
Does this work?

```
bundle exec figaro heroku:set -e production
```

**Comment by KikoH** [comment]
bundle exec figaro heroku:set -e production

Worked for me.

**Comment by liang90925** [comment]
Hi Steven,

Thanks that worked. Do you know how can we get rid of bundle exec?

Thanks

**Comment by Steven3000** [comment]
Bundle exec is a command that performs an action, it's possibly another gem you are running thats giving u the issue.

**Comment by singchow** [comment]
Encounter "figaro: command not found" when running "figaro heroku:set -e production".

Solved it by running "bundle exec figaro heroku:set -e production", thanks to @laserlemon
