### ISSUE TITLE
Figaro install makes me the app unstartable

### ISSUE THREAD

**Issue by emiliog** [laserlemon/figaro#167]
After the installation the rails app won't start anymore. I leaved the application.yml file untouched but the error still occurs. I'm working with Rails 4.1.0.rc1

The error trace is the following: 

/Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/figaro-1.0.0/lib/figaro/rails/application.rb:17:in `rails_not_initialized!': Figaro::RailsNotInitialized (Figaro::RailsNotInitialized)
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/figaro-1.0.0/lib/figaro/rails/application.rb:7:in`default_path'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/figaro-1.0.0/lib/figaro/application.rb:15:in `block in path'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/figaro-1.0.0/lib/figaro/application.rb:15:in`fetch'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/figaro-1.0.0/lib/figaro/application.rb:15:in `path'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/figaro-1.0.0/lib/figaro/application.rb:56:in`raw_configuration'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/figaro-1.0.0/lib/figaro/application.rb:64:in `global_configuration'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/figaro-1.0.0/lib/figaro/application.rb:32:in`configuration'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/figaro-1.0.0/lib/figaro/application.rb:42:in `each'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/figaro-1.0.0/lib/figaro/application.rb:36:in`load'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/figaro-1.0.0/lib/figaro.rb:23:in `load'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/figaro-1.0.0/lib/figaro/rails/railtie.rb:5:in`block in class:Railtie'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.1.0.rc1/lib/active_support/lazy_load_hooks.rb:36:in `call'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.1.0.rc1/lib/active_support/lazy_load_hooks.rb:36:in`execute_hook'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.1.0.rc1/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.1.0.rc1/lib/active_support/lazy_load_hooks.rb:44:in`each'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.1.0.rc1/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.0.rc1/lib/rails/application.rb:121:in`initialize'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.0.rc1/lib/rails/railtie.rb:171:in `new'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.0.rc1/lib/rails/railtie.rb:171:in`instance'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.0.rc1/lib/rails/application.rb:90:in `inherited'
    from /Users/hernanalbano/Documents/Proyectos/ntrada/config/application.rb:10:in`module:Ntrada'
    from /Users/hernanalbano/Documents/Proyectos/ntrada/config/application.rb:9:in `<top (required)>'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.0.rc1/lib/rails/commands/commands_tasks.rb:79:in`require'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.0.rc1/lib/rails/commands/commands_tasks.rb:79:in `block in server'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.0.rc1/lib/rails/commands/commands_tasks.rb:76:in`tap'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.0.rc1/lib/rails/commands/commands_tasks.rb:76:in `server'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.0.rc1/lib/rails/commands/commands_tasks.rb:40:in`run_command!'
    from /Users/hernanalbano/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.0.rc1/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:4:in`require'
    from bin/rails:4:in `<main>'

...

**Comment by txssseal** [comment]
fixed this issue by upgrading to 4.1.0
