### ISSUE TITLE
Deploying to different remotes/apps

### ISSUE THREAD

**Issue by wrburgess** [laserlemon/figaro#173]
How do you specify the Heroku app for figaro deployment?

My local repo has two remotes: `staging` and `production` which point to two different apps on heroku

When I run `figaro heroku:set -e staging` it only deploys to my default heroku app (staging).

How do I specify the production remote?

**Comment by thebucknerlife** [comment]
-e flag specifies the environment inside your application.yml file

you can use the -a flag to specify which heroku app to deploy to

for example:

```
$ figaro heroku:set -e staging -a your-app-staging
```

would deploy your figaro env variables (including the staging specific ones) to your heroku app `your-app-staging.herokuapp.com`

**Comment by laserlemon** [comment]
Thanks @thebucknerlife, that's absolutelt right.
