### ISSUE TITLE
Encountered "undefined method `require_keys' for Figaro:Module (NoMethodError)"

### ISSUE THREAD

**Issue by bfaguy** [laserlemon/figaro#176]
In my `config/initializers/figaro.rb`
I put:
```
Figaro.require_keys("MANDRILL_API_KEY")
```
but got the following:
```
Exiting
/Users/guycao/code/oms_on_rails/config/initializers/figaro.rb:1:in `<top (required)>': undefined method `require_keys' for Figaro:Module (NoMethodError)
        from /Users/guycao/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:241:in `load'
        from /Users/guycao/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:241:in `block in load'
        from /Users/guycao/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /Users/guycao/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:241:in `load'
...
```
Figaro version - 0.7.0
Ruby version - ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
Rails version - 4.1.2

For your information, the environmental variable does exist in the `application.yml`
but even if it didn't exist, it shouldn't complain about not being able to find the `require_keys` method.

Am I missing something? Maybe a `require 'figaro'`?

**Comment by laserlemon** [comment]
Hi @bfaguy, thanks for posting the issue and the supporting information. The first section of the current [readme](https://github.com/laserlemon/figaro#readme) directs Figaro 0.7.0 users to the [old readme](https://github.com/laserlemon/figaro/tree/0-stable#readme). You'll see that the `require_key` method doesn't exist until version 1.0.

**Comment by bfaguy** [comment]
@laserlemon thank you
