### ISSUE TITLE
integer in yaml crashes figaro heroku:set

### ISSUE THREAD

**Issue by johnrees** [laserlemon/figaro#179]
if `application.yml` looks like
```
database_port: 9000
```

running `figaro heroku` raises the error

```
figaro/cli/heroku_set.rb:7:in `system': no implicit conversion of Fixnum into String (TypeError)
```

but running `heroku config:set database_port=9000` would be ok

**Comment by joshco** [comment]
try quoting the value, eg "9000"

**Comment by johnrees** [comment]
Yep that works, just thought I'd raise the bug. Ta

**Comment by johnrees** [comment]
Ah, in fairness, figaro does give a warning to use strings when i run rake tasks too.
