### ISSUE TITLE
Memory leak in Figaro::ENV#get_value ?

### ISSUE THREAD

**Issue by lacco** [laserlemon/figaro#189]
I am currently trying to find a memory leak in my Rails application, and it seems to me that figaro might be one of the problems. Currently, ```Figaro.env.XX``` is called in each request to read some information like the application's domain, which leads to an increasing memory usage.

### Profiling results

For profiling purposes I am using https://github.com/schneems/derailed_benchmarks with https://github.com/SamSaffron/memory_profiler (```PATH_TO_HIT=/de TEST_COUNT=20 bundle exec rake -f perf.rake perf:mem ```) which produces the following output:

```
allocated memory by gem
-----------------------------------
  15973560  figaro-1.0.0
   6696180  activesupport-4.2.1
   6194520  actionview-4.2.1
   5291980  actionpack-4.2.1
     [...]

allocated memory by file
-----------------------------------
  15973560  /Users/user/.rvm/gems/ruby-2.2.1@myproject/gems/figaro-1.0.0/lib/figaro/env.rb
   3880480  /Users/user/.rvm/gems/ruby-2.2.1@myproject/gems/i18n-0.7.0/lib/i18n.rb
   3427320  /Users/user/.rvm/gems/ruby-2.2.1@myproject/gems/activesupport-4.2.1/lib/active_support/core_ext/string/output_safety.rb
   2576880  /Users/user/.rvm/gems/ruby-2.2.1@myproject/gems/actionview-4.2.1/lib/action_view/helpers/translation_helper.rb
     [...]

allocated objects by gem
-----------------------------------
    180060  figaro-1.0.0
     49346  actionview-4.2.1
     45685  activesupport-4.2.1
     38881  actionpack-4.2.1
     17307  newrelic_rpm-3.9.9.275
     [...]

Allocated String Report
-----------------------------------
     70222  "UTF-8"
     69480  /Users/user/.rvm/gems/ruby-2.2.1@myproject/gems/figaro-1.0.0/lib/figaro/env.rb:41
       240  /Users/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/logger.rb:513
        80  /Users/user/.rvm/gems/ruby-2.2.1@myproject/gems/loofah-2.0.1/lib/loofah/html/document_fragment.rb:20
     [...]

     11533  ""
      5940  /Users/user/.rvm/gems/ruby-2.2.1@myproject/gems/figaro-1.0.0/lib/figaro/env.rb:41
       620  /Users/user/.rvm/gems/ruby-2.2.1@myproject/gems/actionpack-4.2.1/lib/action_dispatch/journey/formatter.rb:37
       600  /Users/user/.rvm/gems/ruby-2.2.1@myproject/gems/actionview-4.2.1/lib/action_view/helpers/tag_helper.rb:146
     [...]
```

### Profiling results 2 (improved Figaro::ENV#get_value)

I am not 100% percent sure how to interpret those results, but my testing revealed that https://github.com/laserlemon/figaro/blob/master/lib/figaro/env.rb#L41 is causing the leak. I replaced the implementation of the method with

```ruby
def get_value(key)
  ::ENV[key.upcase]
end
```

and the profiling results were looking much better:

```
allocated memory by gem
-----------------------------------
   3348290  activesupport-4.2.1
   3097500  actionview-4.2.1
   2646030  actionpack-4.2.1
     [...]
     88610  figaro-1.0.0
     [...]

allocated memory by file
-----------------------------------
   1940240  /Users/user/.rvm/gems/ruby-2.2.1@myproject/gems/i18n-0.7.0/lib/i18n.rb
   1713660  /Users/user/.rvm/gems/ruby-2.2.1@myproject/gems/activesupport-4.2.1/lib/active_support/core_ext/string/output_safety.rb
     [...]
     88610  /Users/user/.rvm/gems/ruby-2.2.1@myproject/gems/figaro-1.0.0/lib/figaro/env.rb

allocated objects by gem
-----------------------------------
     24676  actionview-4.2.1
     22845  activesupport-4.2.1
     19441  actionpack-4.2.1
     [...]
       810  figaro-1.0.0
     [...]
```

### How to proceed?

Obviously, a direct lookup in the ```ENV``` hash is much more memory efficient than iterating over all keys and downcasing them. Since Figaro allows case-insensitive access to environment variables, this change would break this feature. I am not into the development plans for figaro, but are there any plans on fixing this? Perhaps figaro could hold an internal representation of the environment allowing accessing it as a hash instead of iterating over all values? This should also be a big performance gain...

**Comment by laserlemon** [comment]
Wow, thank you for the thorough report! :clap: My only nitpick is the lack of [animated GIF](https://github.com/laserlemon/figaro/blob/v1.1.0/CONTRIBUTING.md#how-do-i-contribute). I'm on it.

![WHAT?](http://www.reactiongifs.com/r/what.gif)

Is it possible for you to migrate your performance test setup into a sharable app so I can reproduce your results? I'd love to get this patched up as soon as possible without losing the case-insensitivity feature.

Thank you!

**Comment by laserlemon** [comment]
Can you also confirm that this is still an issue on the latest version of Figaro? You're using version 1.0.0 rather than 1.1.0, although I doubt it will make a difference.
