### ISSUE TITLE
Use strings for Figaro configuration in version 1.1.1

### ISSUE THREAD

**Issue by cnicolaou** [laserlemon/figaro#192]
I've wrapped all of the values inside application.yml file with quotes, yet Figaro keeps displaying the following warning message: `WARNING: Use strings for Figaro configuration.` despite the fact that I've already done so.

I've forked the gem and tried to work out which line (key/value) was causing the warning to appear but everything seems ok when comparing with the documentation provided with the gem.

Not entirely sure what to do here. The warning appears 3 times upon launching the app or any other command that causes the app to initialise.

For further info, I am running the following versions of Rails 3.2.20 and Ruby 2.1.3p242

**Comment by laserlemon** [comment]
What does your `application.yml` look like (sensitive information obfuscated)? Are you using Spring?

**Comment by laserlemon** [comment]
The warning message should also be telling you what key or value needed to be converted to a string. What does it say?

**Comment by cnicolaou** [comment]
> On 7 May 2015, at 13:12, Steve Richert <notifications@github.com> wrote:
> 
> What does your application.yml look like (sensitive information obfuscated)?
> 
`
defaults: &defaults
  application_name: "railsapp"
  resque_password: "xxxx"

development:
  <<: *defaults
  "host": "localhost"
  "asset_host": "localhost:3000"
  "download_url": "download.apphost"
  "appname_url": "http://apphost"
  "redis_server_url": "localhost:3000"
  "secret_token": "1cc391d5964c0873ed68ba898e97f80d..."
  "es":
    "url": "http://127.0.0.1:9200"
    "active": "false"
    "use_resque": "false"
    "index_prefix": "development_"
  "aws":
    "access_key_id":     "access_key_id"
    "secret_access_key": "secret_access_key"
    "bucket_name":       "bucket_name"
  "ses_smtp":
    "access_key_id":     "access_key_id"
    "secret_access_key": "secret_access_key"
  "linkedin":
    "client_id":         "client_id"
    "client_secret":     "client_secret"
    "redirect_uri":      "redirect_uri"
`

> Are you using Spring?
> 
No, I am not using Spring

**Comment by cnicolaou** [comment]
@laserlemon the message is showing AW/SMTP keys, even though they are set to follow the documentation in Figaro.

**Comment by laserlemon** [comment]
The issue is that Figaro doesn't support nested structures. The warning is trying to tell you that the value for `"aws"` is a hash rather than a string and that the value will be converted to the string representation of that hash (`Hash#to_s`).

There's a not about this at the bottom of the [example section](https://github.com/laserlemon/figaro#example) of the readme.

Your configuration file should be a simple key/value mapping, with the exception of Rails-environment-specific configurations, which are nested under a key for the current `Rails.env`.

I hope that helps! Let me know if you have any more questions.

**Comment by cnicolaou** [comment]
@laserlemon great, that explains the warning pretty much after the update.

I've been running Figaro with the nested config for quite some time now, although not supported (officially) but it works like a charm.

**Comment by laserlemon** [comment]
I have no idea how that could have ever been working. But okay!
