### ISSUE TITLE
Just curious, why did you name this figaro?

### ISSUE THREAD

**Issue by bvsatyaram** [laserlemon/figaro#198]
Dear @laserlemon : I am just curious why you named the gem figaro. Is there any particular significance.
I am sorry for the off topic question.

**Comment by MasterSlowPoke** [comment]
If I had to guess, it has something to do with con**FIG**uration.

**Comment by redconfetti** [comment]
:smile:

**Comment by oliverbarnes** [comment]
this should be pinned

**Comment by laserlemon** [comment]
🔨 @MasterSlowPoke nailed it.
