### ISSUE TITLE
Should Figaro work with Ruby 1.8.7 & Rails 2.3.x? (it doesn't)

### ISSUE THREAD

**Issue by armandofox** [laserlemon/figaro#207]
With a Rails 2.3.18 app (including the [simple changes needed for using Bundler](http://bundler.io/rails23.html)), a simple `config/application.yml`, and Figaro in the Gemfile, within  `script/console` I get nil values for all the keys set in `application.yml`.  Rubygems.org specifies no dependencies on either Ruby or Rails version for Figaro, so I assume this **should** work.

I created [this test app](https://github.com/armandofox/figaro-rails2-test) by:

* creating new app using `rails figaro-rails2-test` 
* make the changes noted above so Bundler will work with it (these changes patch Rails to `require` all gems at app boot time)
* add Figaro to the Gemfile and run `bundle install`
* `script/console` to drop into console and examine `Figaro.env.test_key` (nil), `ENV['test_key']` (also nil), etc.

Further, executing `Figaro.load` in console raises `NotImplementedError`.

It may be that I shouldn't expect this to work with an older Ruby/Rails version, but if that's the case it would be good to note that on Rubygems.

**Comment by jgordor** [comment]
Same here, allways getting nil, some news?

**Comment by laserlemon** [comment]
Sorry, Figaro is only maintained to support Rails >= 3.0.
