### ISSUE TITLE
ENV empty: variables not set after production deployment

### ISSUE THREAD

**Issue by rhannequin** [laserlemon/figaro#210]
Hello,

I am trying to deploy my project on a private server with Capistrano. I am using [capistrano-figaro-yml](https://github.com/ChouAndy/capistrano-figaro-yml) to automatically upload my `application.yml` file as a shared file, but that's just a detail. I am not sure my issue is a real issue of Figaro, but I am looking for help.

My issue is that the object `ENV` is empty of my values from `application.yml` when I try to launch Rails as server or console. I tested the content of `ENV` in both `config/initializers/devise.rb` and `config/application.rb` files.

**Edit**: another strange behaviour, I edited my `config/initializers/devise.rb` to avoid the exception from Devise, `rails console` launches and my `ENV` values are available. Is it a normal behaviour in Figaro not to have the values inside initializers but only once the application is properly launched?

What I don't understand, is that it works perfectly on my laptop, in both development and production environments. I removed the symbolic link created by Capistrano to write my own `application.yml` file to check if it wasn't the symbolic link that didn't work, but no changes. I can access `Figaro.env` so Figaro is properly loaded, but keeps being empty from my values. I installed the last versions of all my gems to be sure, nothing happened.

I looked deeply (at least I think I did) on the Internet to find anyone with my issue, but as I don't find lots of answers, I guess the issue is from me, but I really can't find where.

Do you have an idea of why `ENV` would be empty? Thank you. And btw, thank you for your amazing job with Figaro, that helped me so much these past few months.

**Comment by laserlemon** [comment]
I've never encountered this behavior. I could take a look if you're able to spin up an example application that demonstrates the behavior. Sorry I can't help more!

**Comment by rhannequin** [comment]
Thank you for your answer.

Sure, my app is open sourced: https://github.com/rhannequin/funky-starter-plus-plus/tree/feature/unicorn. The exception is throwed from [`config/initializers/devise.rb`](https://github.com/rhannequin/funky-starter-plus-plus/blob/feature/unicorn/config/initializers/devise.rb#L7), where `ENV['DEVISE_SECRET_KEY']` is supposed to be defined from [`config/application.yml`](https://github.com/rhannequin/funky-starter-plus-plus/blob/feature/unicorn/config/application.example.yml#L34) (here example file). I found that `ENV` was also empty of my values (only usual environment variables but not from Figaro) in [`config/application.rb`](https://github.com/rhannequin/funky-starter-plus-plus/blob/feature/unicorn/config/application.rb). And as I said, when I replaced the `ENV` value in [config/initializers/devise.rb](https://github.com/rhannequin/funky-starter-plus-plus/blob/feature/unicorn/config/initializers/devise.rb#L7) to avoid the exception, my app launched properly and `ENV` was full of values.

This issue happens only on my web server after deploying with Capistrano, `config/application.yml` file is a symbolic link from the shared directory (and I checked, the issue is not from the symbolic link).

Thank you for your help.

**Comment by dcmorse** [comment]
I see a similar behavior in a totally different app. If I look in ENV within devise.rb, it doesn't have ENV['SECRET_KEY_BASE'] set. If I survive to the rails console, it's there. Someone is sanitizing the environment passed to the setup?

**Comment by AmitPatel-BoTreeConsulting** [comment]
I am facing same issue with `config` gem in Rails 4.2.5 app. I understand this might not be a right place to raise issues of other gems, but there is something common in both gems, may be loading behavior.

Issue is posted http://stackoverflow.com/questions/35698111/settings-returns-nil-for-all-configurations-which-reads-from-environment-variabl
