### ISSUE TITLE
Rake db:migrate wont run if figaro included in gem file

### ISSUE THREAD

**Issue by kgathi2** [laserlemon/figaro#214]
I added figaro to my project and all worked well until i tried doing a `rake db:drop db:create db:migrate`

The first two were successful but `rake db:migrate` wont work. If a comment out figaro in the gem file, it works. 

At one point when i migrated my db, it reversed all the migrations to Version=0. I think this is related as well.

**Comment by kgathi2** [comment]
After racking my brains out, it turns out me suspicions were right, but not figaro's fault. It was acting like that because i had the following variable in my application.yml

`VERSION: '0.0.1'`

So i figured rails allows configuration via env variables, but i had no idea this was one of them. Cost me my entire staging db!!!!!
I wonder which others are configurable

**Comment by laserlemon** [comment]
There's no telling what ENV variable collisions there could be so I err on the side of explicit rather than generic variable names. Glad you found the cause!
