### ISSUE TITLE
figaro heroku:set doesn't work

### ISSUE THREAD

**Issue by alexvbush** [laserlemon/figaro#218]
Hey guys, I'm trying to follow the `README` and am getting an error when I run `bundle exec figaro heroku:set admin=alex -e production`

`ERROR: "figaro heroku:set" was called with arguments ["admin=alex"]`
`Usage: "figaro heroku:set"`

What am I doing wrong?

Thanks.

**Comment by connorjacobsen** [comment]
I am also getting this error:

```bash
figaro heroku:set -e production
~/.rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/cli/task.rb:28:in `system': no implicit conversion of Fixnum into String (TypeError)
```

**Comment by laserlemon** [comment]
`figaro heroku:set` uses your values in `application.yml`. You do not set them on the command line. If you want to set them via command line, you can use `heroku config:set` directly instead.

@connorjacobsen Make sure all the values in `application.yml` are strings, no integers.

**Comment by alexvbush** [comment]
@laserlemon thanks, makes sense. I guess for some reason @connorjacobsen and I thought that `figaro heroku:set` should set local and heroku values all together from the `README`.
