### ISSUE TITLE
Defining uppercase/ capital env vars

### ISSUE THREAD

**Issue by TheNotary** [laserlemon/figaro#223]
I'm following along with a tut on aws, which has a system where I can either define an config/aws.yml file containing sensative information, or I can define some env vars.  I think I'd like all my sensative stuff mostly in figaro's application.yml file for now, but aws demands that the env vars be uppercase, eg

```
AWS_ACCESS_KEY_ID: 'blahblah'
AWS_SECRET_ACCESS_KEY: 'keykey'
```

Those aren't exposed as ENV['AWS_ACCESS_KEY_ID'], etc, though.  I can't see any information on this issue, so apparently I'm the first to encounter it??  My workaround will be to create an initializer that set's the lowercase env values to uppercase (or make the aws config file... can't decide which new file is best ;).  

How come application.yml variables made in all caps don't show up in my environment btw?

**Comment by KaoruDev** [comment]
@TheNotary so I had the same issue, turns out it was spring, if you run `bundle exec spring stop` and restart the `ENV` should be uppercased.

**Comment by TheNotary** [comment]
It started happening to an app of mine continually, found more data here
http://stackoverflow.com/questions/29195489/rails-4-1-environment-variables-not-reloading

What are the maintainer's opinions towards doing something like `Spring.watch "config/application.yml"` to ensure vars are causing a reboot of the app?

**Comment by TheNotary** [comment]
closing per #119 looks like this has been a long drawn battle between spring and figaro =/
