### ISSUE TITLE
variables with multiple values.

### ISSUE THREAD

**Issue by NafaaBout** [laserlemon/figaro#224]
In yaml, there is the posibility to define keys with multiple values, and when you load the file you get an array of values for that key. 
for example: 
```
proxies:
  - proxy-one.proxy.com
  - proxy-two.proxy.com
```
if I load this file using YAML.load, I'll get what I expect. But if I  put it in application.yml, I get the first value only.
is this a bug or intentional behavior?

**Comment by jampow** [comment]
I have the same doubt

**Comment by jampow** [comment]
to solve my problem I setted:
`proxies: "proxy1;proxy2"`

and called the split method
`ENV['proxies'].split(";")`

please, let me know if there is a better way!

**Comment by laserlemon** [comment]
The `README.md` mentions this deficiency. `ENV` is only capable of storing _string_ keys and values. It's a basic limitation of `ENV`. You'd have to split them at runtime, as mentioned by @jampow. Thank you!
