### ISSUE TITLE
Disable string conversion warning

### ISSUE THREAD

**Issue by hlascelles** [laserlemon/figaro#226]
We like to keep some values in our yml as integers and booleans (IDE highlighting etc). We fully understand that ENVs are intrinsically strings, and understand they will be converted.

So, for us, seeing the `WARNING: Use strings for Figaro configuration` on startup is a bit noisy.

If we were to make a PR for that not happen, how would you like us to do it? By passing in another ENV? Making it the first ENV in the yml file? Something else?

**Comment by laserlemon** [comment]
I think I'd do this by adding another value to `application.yml` and prepending the configuration with `FIGARO_` or similar. Like… `FIGARO_SILENCE_STRING_WARNINGS`. No need to make it the first value. We can just look for that value first. Feel free to work on this and open a PR if you're still interested. Thank you!
