### ISSUE TITLE
support for rails 5

### ISSUE THREAD

**Issue by u007** [laserlemon/figaro#230]
hi,

im getting:
Psych::SyntaxError: (<unknown>): found character that cannot start any token while scanning for the next token at line 12 column 12
/usr/local/rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/application.rb:60:in `parse'
/usr/local/rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/application.rb:56:in `block in raw_configuration'
/usr/local/rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/application.rb:56:in `yield'
/usr/local/rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/application.rb:56:in `raw_configuration'
/usr/local/rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/application.rb:64:in `global_configuration'
/usr/local/rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/application.rb:32:in `configuration'
/usr/local/rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/application.rb:42:in `each'
/usr/local/rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/application.rb:36:in `load'
/usr/local/rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro.rb:23:in `load'
/usr/local/rvm/gems/ruby-2.2.2/gems/figaro-1.1.1/lib/figaro/rails/railtie.rb:5:in `block in <class:Railtie>'
...

**Comment by laserlemon** [comment]
It looks like your YAML is probably invalid. Feel free to paste a _sanitized_ version of your `application.yml` here to get another set of :eyes: on it.

**Comment by u007** [comment]
awesome, 
i accidently put in @ and $ in the value within application.yml
