### ISSUE TITLE
This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs

### ISSUE THREAD

**Issue by rakibai** [laserlemon/figaro#243]
This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs

**Comment by rakibai** [comment]
No..it is not cleared
Error
You are not logged in: You are not logged in. Please log in and try again.

**Comment by laserlemon** [comment]
Please read and follow the [contribution guidelines](https://github.com/laserlemon/figaro/blob/master/CONTRIBUTING.md#bug-reports). I need more information than a copied/pasted error message. I need enough information to move me from having zero knowledge of your particular issue to reproducing the issue consistently on my own machine.

**Comment by rakibai** [comment]
The requested URL /Ignore the Not Found error and Copy Above URL it is your
access token www.facebook.com was not found on this server.
------------------------------
Apache/2.2.3 (Red Hat) Server at account.nokia.com Port 80
