### ISSUE TITLE
Rails 5

### ISSUE THREAD

**Issue by romariolopezc** [laserlemon/figaro#246]
Is this working with rails 5?

**Comment by TheNotary** [comment]
And are you getting burnt out maintaining this @laserlemon?  Looks like the merges haven't been done in a while.  

I really love this code base, even using it outside of rails is pretty awesome just for setting up configuration files.

**Comment by iamjhu** [comment]
I haven't tested all of the features but I can confirm the basics (i.e., declaring ENVs)  of Figaro works on Rails 5.
