### ISSUE TITLE
Figaro 2

### ISSUE THREAD

**Issue by seanfcarroll** [laserlemon/figaro#272]
Just wondering if there is a timeline for Figaro 2? I see there has been a lot of work on the v2 branch.

**Comment by laserlemon** [comment]
Yeah, I feel pretty awful about how little time I've been able to devote to Figaro lately. I'm still very excited about Figaro 2, but between kids and work, spare development time is hard to come by. I'm hopeful to carve out some recurring OSS time soon.

**Comment by seanfcarroll** [comment]
I know the feeling. I'm involved with Ransack and it's the same thing. By the way, we signed up for Open Collective, and there some [money coming in](https://github.com/activerecord-hackery/ransack#sponsors). We plan to use it to fund some coding work via Upwork.

**Comment by laserlemon** [comment]
Thanks for the heads up. Very cool. I'll likely pursue something like that once I know I have space for some followthrough.
