### ISSUE TITLE
application.yml overrides explicitly passed environment variables

### ISSUE THREAD

**Issue by halgorithm** [laserlemon/figaro#44]
It seems that environment variables defined within the application.yml file override ones explicitly passed into rails commands. For example, if my application.yml has `TEST_VAR: 3` and I run `TEST_VAR=100 rails server` from the command line, trying `ENV['TEST_VAR']` within my Rails app returns 3 instead of 100 (as I would expect).

I think this functionality is important because, for example, our team has several developers that each need to share localhost on different domains (for testing on IE/mobile). The "main" domain for the site comes from a single environment variable that we'd like to easily change for each person.

**Comment by mikeycgto** [comment]
It was definitely merged. Not sure if it got released. Maybe @laserlemon knows?

**Comment by ctro** [comment]
Bump.  The only information I see about overriding Figaro ENV vars is here in this thread.  Is this possible with Figaro?

**Comment by ziaulrehman40** [comment]
anything?
