### ISSUE TITLE
AWS Elastic Beanstalk Deployment Issue

### ISSUE THREAD

**Issue by ajporterfield** [laserlemon/figaro#52]
I have a Rails 3 app deployed on Amazon's Elastic Beanstalk solution.  When I'm developing locally, my ENV variables defined in config/application.yml are set correctly; however, they're non-existent in production.  This gem isn't only for Heroku deployment, correct?  Has anyone used this gem in EB (Elastic Beanstalk)?  If so, were there any gotchas to get it to work?

Thanks!

**Comment by deepakazad** [comment]
Any plans of supporting figaro for aws ?

**Comment by manolo07** [comment]
That would be awesome!, how can I help?
