### ISSUE TITLE
Using figaro without Rails loaded

### ISSUE THREAD

**Issue by chipairon** [laserlemon/figaro#77]
Hello,

I am working on a project with Rails 4 and Capistrano 3 and I am using Figaro to handle the configuration variables.

When I try to access Figaro variables from a Capistrano task I have found this caveat:

To use Figaro.env I have to load Rails first (which capistrano 3 is not doing by default). I do so like this:

```
#config/deploy/staging.rb
ENV["RAILS_ENV"] = "staging" # This is necessary or Rails.env will be "development" and Figaro will use development vars instead of staging.
require File.expand_path('../environment',  __FILE__) 
```

Is there a way to make figaro do its thing (make variables for a certain environment accessible as ENV["blah"]) without loading Rails?

Isn't it possible to expose the functionality in a public method and then if the gem is used by Rails, call this method in the hook as you do now?

**Comment by kpheasey** [comment]
In case anyone else stumbles across this.  you just need the following in your Capfile

```ruby
# Load ENV vars via Figaro
require 'figaro'
Figaro.application = Figaro::Application.new(environment: 'production', path: File.expand_path('../config/application.yml', __FILE__))
Figaro.load
```

**Comment by b-long** [comment]
What about for someone writing a non-Rails and non-Capistrano ruby application?

**Comment by laserlemon** [comment]
@b-long Check out the `v2` branch. So far, it doesn't depend on Rails at all. Any Ruby application will work.

**Comment by b-long** [comment]
Great :) Thanks, @laserlemon !

**Comment by thbar** [comment]
Re `v2` @laserlemon that's great news! Do you already have a rough idea when this will be released as a gem (even as `--pre`), to make it easier to use it directly from `add_development_dependency`? Thanks!

**Comment by laserlemon** [comment]
I don't have a firm timeline yet although I'll be working on this on March 31 and am hopeful that getting a prerelease could happen on that day.
